title: So they say
author: brian kariuki
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
Hello there, I'm Brian.
Remember to write more stuff

# social links
twitter_username: @briokariuki # DO NOT include the @ character, or else the build will fail!
github_username:  kariukibrian # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
