theme: minima
title: So they say
author: kariuki brian
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  update description

# social links
twitter_username: briokariuki # DO NOT include the @ character, or else the build will fail!
github_username:  kariukibrian # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
